#!/bin/bash

if [ -f "$1" ]
then
    echo File exists
else
cat > "$1" <<- SimpleSource
#!/usr/bin/env python3

from ten import *


@entry
def main():
    ...


main()
SimpleSource
fi

chmod +x -- "$1"
code -- "$1"